Модуль 9
htmlacademy-univer-javascript-1/2221361-kekstagram-1 pull request #10
Opened 2022-12-06 16:12 UTC by M1s71ka

2022-12-07 14:10 UTC, GennadiyM requested changes

2022-12-07 14:10 UTC, GennadiyM commented on js/form.js
> +  if (scaleField.value === '25%') {
магическое число

2022-12-07 14:10 UTC, GennadiyM commented on js/form.js
> +  if (scaleField.value === '100%') {
магическое число

2022-12-07 14:10 UTC, GennadiyM commented on js/form.js
> +  scaleField.value = '100%';
магическое число

2022-12-07 14:10 UTC, GennadiyM commented on js/slider.js
> +    case 'effect-none':
'effect-none',   'effect-chrome', 'effect-sepia' вынести в перечисление констант Filter = { CHROME: 'effect-chrome' и тд

2022-12-07 14:10 UTC, GennadiyM commented on js/slider.js
> +        updateImageStyle('grayscale');
все фильтры тоже вынести в перечисление констант

2022-12-07 14:10 UTC, GennadiyM commented on js/form.js
>    commentField.addEventListener('input', onSubmitButton);
одинаковые обработчики на двух разных элементах (перечитываем критерии)

2022-12-07 14:10 UTC, GennadiyM commented on js/form.js
>  function onUploadPhoto() {
почему объявлена как function? (перепроверить, возможно ее можно использовать как стрелочную) Внтри нет логики проверки тот ли тип файла используется

2022-12-07 14:10 UTC, GennadiyM commented on js/form.js
>    validateForm();
а где используется сама функция uploadPhoto? Она экспортируется, но я что-то не нашел, где она импортируется

2022-12-07 14:10 UTC, GennadiyM commented on js/slider.js
> +  effectsContainer.addEventListener('click', onEffectClick);
effectsContainer.addEventListener('click', onEffectsContainerClick);

2022-12-07 14:10 UTC, GennadiyM commented on js/slider.js
> +      });
и при каждом клике будет вешаться новый обработчик апдейта слайдера?

2022-12-07 14:10 UTC, GennadiyM commented on js/slider.js
> +      });
Нужно перепродумывать логику, это крайне плохое решение

2022-12-08 13:59 UTC, M1s71ka commented on js/form.js
>    validateForm();
Импортируется в main.js

2022-12-10 18:28 UTC, GennadiyM requested changes

2022-12-10 18:28 UTC, GennadiyM commented on index.html
> +  <script src="nouislider/nouislider.js"></script>
почему без type

2022-12-10 18:28 UTC, GennadiyM commented on js/constants.js
> +const SCALE_STEP = 25;
вот это можно убрать

2022-12-10 18:28 UTC, GennadiyM commented on js/constants.js
> +};
Scale =  {MIN, STPEP, MAX}

2022-12-10 18:28 UTC, GennadiyM commented on js/form.js
> +}
кончено очень мудрена логика, можно было проще сделать ( в лекции был пример)

2022-12-10 18:28 UTC, GennadiyM commented on js/form.js
> +  biggerButton.disabled = true;
нужно быть внимательнее, блокировка при запуске может сыграть злую шутку

2022-12-10 18:28 UTC, GennadiyM commented on js/form.js
> +  validateForm();
не забыть, что в будущем валидацию надо будет перенести в другое место

2022-12-10 18:28 UTC, GennadiyM commented on js/slider.js
> +  if (effect !== 'none') {
могический none

2022-12-10 18:28 UTC, GennadiyM commented on js/slider.js
> +  if (previewImage.classList.item(1)) {
магическая 1

2022-12-10 18:28 UTC, GennadiyM commented on js/slider.js
> +  }
скорее всего здесь же надо будет еще и effectParametr в исходное вернуть

2022-12-12 06:16 UTC, GennadiyM approved these changes

2022-12-12 06:16 UTC, merged